<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<% request.setAttribute("pageTitle", "Thêm sản phẩm"); request.setAttribute("activeMenu", "product"); %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Thêm Sản phẩm | Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin-layout.css"><style>.wrap{max-width:900px;margin:0 auto}.card{border:0;border-radius:8px;box-shadow:0 4px 18px rgba(0,0,0,.06)}</style></head><body><div class="admin-layout"><%@ include file="fragments/sidebar.jsp" %><div class="admin-main"><%@ include file="fragments/header.jsp" %><main class="admin-content"><div class="wrap"><div class="mb-3"><a href="${pageContext.request.contextPath}/admin/product/list" class="btn btn-outline-secondary btn-sm"><i class="fa-solid fa-arrow-left"></i> Quay lại</a></div><div class="card"><div class="card-header bg-white"><h5 class="mb-0">Thêm sản phẩm</h5></div><div class="card-body">
<c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<form method="post" enctype="multipart/form-data">
<div class="row g-3"><div class="col-md-8"><label class="form-label">Tên sản phẩm *</label><input name="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Danh mục *</label><select name="categoryId" class="form-select" required><option value="">Chọn danh mục</option><c:forEach items="${categories}" var="c"><option value="${c.id}">${c.name}</option></c:forEach></select></div><div class="col-md-4"><label class="form-label">Giá *</label><input type="number" min="0" step="1000" name="price" class="form-control" required></div><div class="col-md-4"><label class="form-label">Tồn kho *</label><input type="number" min="0" name="stockQuantity" class="form-control" required></div><div class="col-md-4"><label class="form-label">Trạng thái</label><select name="active" class="form-select"><option value="true">Đang bán</option><option value="false">Ngừng bán</option></select></div><div class="col-12"><label class="form-label">Mô tả</label><textarea name="description" rows="4" class="form-control"></textarea></div><div class="col-md-6"><label class="form-label">Upload ảnh</label><input type="file" name="imageFile" class="form-control" accept="image/*"></div><div class="col-md-6"><label class="form-label">Hoặc nhập URL ảnh</label><input name="imageUrl" class="form-control" placeholder="https://..."></div></div>
<div class="mt-4"><button class="btn btn-primary"><i class="fa-solid fa-floppy-disk"></i> Lưu sản phẩm</button> <a href="${pageContext.request.contextPath}/admin/product/list" class="btn btn-outline-secondary">Hủy</a></div>
</form></div></div></div></main></div></div></body></html>
